### PR TITLE
Restaurant Page

### PR DESCRIPTION
**Pull request by uryelah**
Restaurant page project:

- javascript bundling with webpack
- dynamically generated content for tabs
- ES6 syntax

### CODE REVIEW

**Review by MauricioRobayo — APPROVED** [review]

**Comment by uryelah** [comment]
Thanks! I didn't notice that hover bug, are you on Chrome? 
Really good feedback, I'll work on the improvements :-)

**Comment by MauricioRobayo** [comment]
And two more things 😄:

* [ ] stickler doesn't seem to be enabled on this repository... make sure to enable it before merging
* [ ] for some reason, all of your files are not showing on this PR, just [three of them](https://github.com/uryelah/Microverse-603-restaurant-page/pull/1/files), and they are not showing all the content, that's why I could not comment directly on those, so make sure you are following the [`git flow guidelines`](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).

**Comment by MauricioRobayo** [comment]
> Thanks! I didn't notice that hover bug, are you on Chrome?
Yes! Chrome it is.

**Comment by uryelah** [comment]
Cool, just notice Stickler, will enable it. I have no idea why only some of the files are showing up though.

**Comment by uryelah** [comment]
Stickler

**Pull request closed without merging**
